name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24.x"
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Test library
        run: npm run test:ngx-loading-buttons

      - name: Build library
        run: npm run build:ngx-loading-buttons
