name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: https://registry.npmjs.org/
          package-manager-cache: false

      - name: Install dependencies
        run: npm ci

      - name: Test library
        run: npm run test:ngx-loading-buttons

      - name: Build library
        run: npm run build:ngx-loading-buttons

      - name: Show package contents
        run: npm pack ./dist/ngx-loading-buttons --dry-run

      - name: Publish package
        run: npm publish ./dist/ngx-loading-buttons --access public
